#!/usr/bin/env python3
"""Rebuild readable prompt docs from executable functions; no inference."""
import json
import sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from nnd.experiment_cli import Experiment, prompt_examples
from nnd.flag_game.prompts import _susceptibility_line as pairwise_guidance
from nnd.flag_game_broadcast.prompts import _susceptibility_line as broadcast_guidance
from nnd.flag_game_org.prompts import social_guidance

ROOT=Path(__file__).resolve().parents[1]
for protocol in ['pairwise','broadcast','manager']:
    parts=[f'# {protocol.capitalize()} executable prompts\n', 'Generated by `python scripts/render_prompt_reference.py`. Do not hand-edit. Empty-memory examples show the full allowed-country list; actual calls substitute histories and crop images. Manager receives no images.\n']
    for m in [1,2,3]:
        parts.append(f'## Bandwidth {m}\n')
        cfg=Experiment(protocol=protocol,message_bandwidth=m)
        for stage,text in prompt_examples(cfg).items():
            parts.append(f'### {stage}\n\n```text\n{text}\n```\n')
    parts.append('## Optional guidance ladder\n\nGuidance is omitted when disabled. Alpha selects these clauses:\n')
    for alpha in [0,.25,.5,.75,1]:
        parts.append(f'### Alpha {alpha}\n')
        if protocol=='manager':
            text='Observer: '+social_guidance(alpha)+'\nManager: '+social_guidance(alpha,manager=True)
        else:text=(pairwise_guidance if protocol=='pairwise' else broadcast_guidance)(alpha)
        parts.append(f'```text\n{text}\n```\n')
    (ROOT/'prompts'/f'{protocol}.md').write_text('\n'.join(parts))
